### ISSUE TITLE
After selecting DirectionalLight and hovering over it, white line does not go away

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/three.js#15]
I can successfully move around the DirectionalLight, but doing so causes a white line to appear (which indicates the direction of the light). That's good, but I can't get that white line to disappear. I expected that unselecting the DirectionalLight would cause that line to disappear. Chrome 53.

**Comment by aymanhab** [comment]
I think we can close this one as addressed by #17 if you agree @chrisdembia

**Comment by chrisdembia** [comment]
This issue is still slightly different from #17. I would expect the DirectionalLight line to appear before selecting it, while Debug is on. However it only appears after selecting/moving the DirectionalLight.
